"""mkfont.py - consume Kimi's V6 castle-voice font for the text renderer.

Reads docs/visual/sprites/font_data.s (Kimi's asset, never modified) and writes
two generated includes next to gate7_castle.s:

  font_eq.inc   KFONT_FACE / KFONT_RELIEF colour equates (from her file)
  font.inc      font_glyphs: her 7-byte bitmask glyphs, copied verbatim
                font_ascii:  256-byte byte -> glyph index table ($FF = blank;
                             $85 = ellipsis, lower case drawn as upper case)

Only the TEXT_ENABLE build (Bob Checkpoint B) includes these.

It also reads Kimi's docs/visual/sprites/hud_icons.s (V6 HUD memory row):

  hud_eq.inc    HUDC_<CAT>_LIT / _DIM and HUD_FLASH colour equates
  hud_icons.inc hud_icons: six 8x8 icons (doors, levers, pace, guards, traps,
                chests), 8 bytes each, copied verbatim

Her equate names carry a stray space ("HUD_DOORS   _LIT"); the parser
tolerates it and the generated names are HUDC_* so nothing collides.

    python tools/mkfont.py [path/to/font_data.s]

Without a path it reads Kimi's file from the working tree, else from git
(KIMI_REF, default kimi/visual-refinement), like mkmsg.py.
"""
import os
import re
import sys

from mkmsg import ELL, kimi_file

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
KIMI_FONT = "docs/visual/sprites/font_data.s"
KIMI_HUD = "docs/visual/sprites/hud_icons.s"
HUD_CATS = ("DOORS", "LEVERS", "PACE", "GUARDS", "TRAPS", "CHESTS")
OUT = os.path.join(ROOT, "gate7_castle")

# Kimi's FONT_ORDER: A-Z 0-9 . , : ; ! ? - + / % ( ) SP ELLIPSIS UP DOWN LEFT RIGHT
ORDER = [chr(c) for c in range(ord("A"), ord("Z") + 1)] + [str(d) for d in range(10)] + \
        list(".,:;!?-+/%()") + [" ", "ELLIPSIS", "UP", "DOWN", "LEFT", "RIGHT"]


def parse(txt):
    face = re.search(r"^FONT_FACE\s+equ\s+(\$[0-9A-Fa-f]+)", txt, re.M)
    relief = re.search(r"^FONT_RELIEF\s+equ\s+(\$[0-9A-Fa-f]+)", txt, re.M)
    if not (face and relief):
        raise SystemExit("font_data.s: FONT_FACE / FONT_RELIEF not found")
    body = txt[txt.index("font_glyphs:"):]
    glyphs = []
    for ln in body.splitlines()[1:]:
        code = ln.split(";")[0]
        if "dc.b" not in code:
            if glyphs and code.strip():
                break
            continue
        vals = re.findall(r"\$([0-9A-Fa-f]{2})", code)
        if len(vals) != 7:
            raise SystemExit("font_data.s: glyph row without 7 bytes: %r" % ln)
        glyphs.append(vals)
    if len(glyphs) != len(ORDER):
        raise SystemExit("font_data.s: %d glyphs, contract says %d" % (len(glyphs), len(ORDER)))
    return face.group(1), relief.group(1), glyphs


def parse_hud(txt):
    cols = {(c, k): v for c, k, v in re.findall(r"^HUD_([A-Z]+)\s*_(LIT|DIM)\s+equ\s+(\$[0-9A-Fa-f]+)", txt, re.M)}
    flash = re.search(r"^HUD_FLASH\s+equ\s+(\$[0-9A-Fa-f]+)", txt, re.M)
    for c in HUD_CATS:
        for k in ("LIT", "DIM"):
            if (c, k) not in cols:
                raise SystemExit("hud_icons.s: no HUD_%s_%s" % (c, k))
    if not flash:
        raise SystemExit("hud_icons.s: no HUD_FLASH")
    icons = []
    for ln in txt[txt.index("hud_icons:"):].splitlines()[1:]:
        code = ln.split(";")[0]
        if "dc.b" in code:
            vals = re.findall(r"\$([0-9A-Fa-f]{2})", code)
            if len(vals) != 8:
                raise SystemExit("hud_icons.s: icon row without 8 bytes: %r" % ln)
            icons.append(vals)
    if len(icons) != len(HUD_CATS):
        raise SystemExit("hud_icons.s: %d icons, contract says 6" % len(icons))
    return cols, flash.group(1), icons


def main_hud():
    txt, src = kimi_file(KIMI_HUD)
    cols, flash, icons = parse_hud(txt)
    o = ["; GENERATED by tools/mkfont.py from Kimi's hud_icons.s - do not edit"]
    for c in HUD_CATS:
        for k in ("LIT", "DIM"):
            o.append("%-20s equ     %s" % ("HUDC_%s_%s" % (c, k), cols[(c, k)]))
    o.append("%-20s equ     %s" % ("HUD_FLASH", flash))
    with open(os.path.join(OUT, "hud_eq.inc"), "w", newline="\n") as f:
        f.write("\n".join(o) + "\n")
    o = ["; GENERATED by tools/mkfont.py from Kimi's hud_icons.s - do not edit", "hud_icons:"]
    for c, v in zip(HUD_CATS, icons):
        o.append("        dc.b    %s   ; %s" % (",".join("$" + x.upper() for x in v), c.lower()))
    o.append("        .even")
    with open(os.path.join(OUT, "hud_icons.inc"), "w", newline="\n") as f:
        f.write("\n".join(o) + "\n")
    print("hud_icons.inc: 6 icons from %s" % src)
    return cols, flash, icons


def main(path=None):
    if path:
        txt, src = open(path, encoding="utf-8", errors="replace").read(), path
    else:
        txt, src = kimi_file(KIMI_FONT)
    face, relief, glyphs = parse(txt)
    with open(os.path.join(OUT, "font_eq.inc"), "w", newline="\n") as f:
        f.write("; GENERATED by tools/mkfont.py from Kimi's font_data.s - do not edit\n")
        f.write("KFONT_FACE      equ     %s\nKFONT_RELIEF    equ     %s\n" % (face, relief))
    table = [0xFF] * 256
    for i, g in enumerate(ORDER):
        if len(g) == 1 and g != " ":
            table[ord(g)] = i
            if g.isalpha():
                table[ord(g.lower())] = i
    table[ELL] = ORDER.index("ELLIPSIS")
    o = ["; GENERATED by tools/mkfont.py from Kimi's font_data.s - do not edit",
         "font_glyphs:"]
    for g, name in zip(glyphs, ORDER):
        o.append("        dc.b    %s   ; %s" % (",".join("$" + v.upper() for v in g), name))
    o.append("font_ascii:")
    for i in range(0, 256, 16):
        o.append("        dc.b    " + ",".join("$%02X" % v for v in table[i:i + 16]))
    o.append("        .even")
    with open(os.path.join(OUT, "font.inc"), "w", newline="\n") as f:
        f.write("\n".join(o) + "\n")
    print("font.inc: %d glyphs from %s" % (len(glyphs), src))
    return glyphs, table


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
    main_hud()
